Repository NewTec-GmbH/pyJiraCli, pull requests merged in 2024-06, with the labels that each got.

#27 Improved CLI
  README.md
  src/pyJiraCli/__main__.py
  src/pyJiraCli/cmd_delete.py
  src/pyJiraCli/cmd_export.py
  src/pyJiraCli/cmd_import.py
  src/pyJiraCli/cmd_login.py
  src/pyJiraCli/cmd_print.py
  src/pyJiraCli/cmd_search.py
Labels: documentation, enhancement

#30 Documentation
  README.md
  pyproject.toml
  setup.cfg
  src/pyJiraCli/cmd_search.py
Labels: documentation

#34 Argparse return code
  src/pyJiraCli/__main__.py
  src/pyJiraCli/printer.py
  src/pyJiraCli/ret.py
Labels: bug, enhancement

#37 CI Tests
  .github/workflows/ci.yml
  .github/workflows/test.yml
  tests/test_empty.py
  tests/test_main.py
Labels: enhancement

#39 Updated link and badge to CI
  README.md
Labels: bug

#40 Reduced timeout
  src/pyJiraCli/jira_server.py
Labels: bug

#41 Return codes and messages
  README.md
  src/pyJiraCli/__main__.py
  src/pyJiraCli/cmd_delete.py
  src/pyJiraCli/cmd_export.py
  src/pyJiraCli/cmd_import.py
  src/pyJiraCli/cmd_login.py
  src/pyJiraCli/cmd_print.py
  src/pyJiraCli/cmd_search.py
  src/pyJiraCli/crypto_file_handler.py
  src/pyJiraCli/file_handler.py
  src/pyJiraCli/jira_issue.py
  src/pyJiraCli/jira_server.py
  src/pyJiraCli/printer.py
  src/pyJiraCli/ret.py
  tests/test_main.py
Labels: bug

#45 Increased timeout of REST requests
  src/pyJiraCli/jira_server.py
Labels: bug

#52 close issue #51
  src/pyJiraCli/cmd_import.py
  src/pyJiraCli/cmd_print.py
  src/pyJiraCli/cmd_search.py
  src/pyJiraCli/jira_server.py
Labels: bug

#50 add --save option to search command
  README.md
  design/context.puml
  design/use_case.puml
  src/pyJiraCli/cmd_export.py
  src/pyJiraCli/cmd_import.py
  src/pyJiraCli/cmd_search.py
  src/pyJiraCli/jira_issue.py
Labels: enhancement

#54 update the documentation
  README.md
  design/context.puml
  design/use_case.puml
Labels: documentation

#55 Generic import command
  README.md
  examples/import_issues/README.md
  examples/import_issues/multiple_issues.json
  examples/import_issues/single_issue.json
  examples/import_issues/sub_issues.json
  src/pyJiraCli/cmd_import.py
Labels: enhancement

#53 use the raw issue dict for export, print and search
  src/pyJiraCli/issue_constants.py
  src/pyJiraCli/jira_issue.py
Labels: enhancement

#62 close issue #61
  src/pyJiraCli/jira_server.py
Labels: bug

#58 56 remove unused constpy file and jira issue class
  src/pyJiraCli/cmd_export.py
  src/pyJiraCli/cmd_print.py
  src/pyJiraCli/issue_constants.py
  src/pyJiraCli/jira_issue.py
Labels: bug

#64 47 drop csv support
  README.md
  design/context.puml
  pyproject.toml
  setup.cfg
  src/pyJiraCli/__main__.py
  src/pyJiraCli/cmd_export.py
  src/pyJiraCli/cmd_print.py
  src/pyJiraCli/file_handler.py
  src/pyJiraCli/ret.py
Labels: bug

#66 close issue
  src/pyJiraCli/cmd_profile.py
Labels: bug, documentation

#71 fix bug
  src/pyJiraCli/cmd_search.py
Labels: bug

#74 fix errors
  src/pyJiraCli/ret.py
Labels: bug

#79 Refactoring
  README.md
  src/pyJiraCli/__main__.py
  src/pyJiraCli/cmd_export.py
  src/pyJiraCli/cmd_get_sprints.py
  src/pyJiraCli/cmd_import.py
  src/pyJiraCli/cmd_print.py
  src/pyJiraCli/cmd_profile.py
  src/pyJiraCli/cmd_search.py
  src/pyJiraCli/jira_server.py
  tests/test_main.py
Labels: enhancement

#85 Feature: create component
  examples/import_issues/README.md
  examples/import_issues/component.json
  src/pyJiraCli/cmd_import.py
Labels: enhancement

#86 Added Python 3.11 support
  .github/workflows/ci.yml
  .github/workflows/online.yml
  pyproject.toml
Labels: enhancement

#80 Documentation/examples
  README.md
  examples/search/README.md
  examples/search/search.bat
  examples/search/search.sh
Labels: documentation

#87 Improved max option documentation
  src/pyJiraCli/cmd_search.py
Labels: documentation

#88 Version fixes
  pyproject.toml
  src/pyJiraCli/cmd_search.py
  src/pyJiraCli/version.py
  tools/create_executable.bat
Labels: documentation, enhancement

#90 89 examples for get sprints
  examples/scripts/README.md
  examples/scripts/track_sprint_progress/README.md
  examples/scripts/track_sprint_progress/track_sprint_progress.py
  examples/sprints/README.md
  examples/sprints/sprints_in_board.json
Labels: documentation

#93 Update README.md
  README.md
  pyproject.toml
  setup.cfg
Labels: documentation

#95 Fixed exception on existing components
  pyproject.toml
  src/pyJiraCli/cmd_import.py
Labels: bug

#100 Get complete worklog from issues when searching.
  pyproject.toml
  src/pyJiraCli/cmd_search.py
Labels: bug

#102 Different parameters for the same
  README.md
  examples/scripts/track_sprint_progress/README.md
  examples/scripts/track_sprint_progress/track_sprint_progress.py
  examples/search/README.md
  src/pyJiraCli/cmd_search.py
  tests/online/test_04_search.py
Labels: enhancement

#103 Feature: filter search
  README.md
  src/pyJiraCli/cmd_export.py
  src/pyJiraCli/cmd_print.py
  src/pyJiraCli/cmd_search.py
  src/pyJiraCli/jira_server.py
  tests/online/test_04_search.py
Labels: enhancement
